INSERT INTO `word` (`theme_id`, `word`, `word_kor`)
VALUES (1, 'bicycle', '자전거'),
       (1, 'car', '차'),
       (1, 'motorcycle', '오토바이'),
       (1, 'airplane', '비행기'),
       (1, 'bus', '버스'),
       (1, 'train', '기차'),
       (1, 'truck', '트럭'),
       (1, 'boat', '보트'),
       (2, 'bird', '새'),
       (2, 'cat', '고양이'),
       (2, 'dog', '개'),
       (2, 'horse', '말'),
       (2, 'sheep', '양'),
       (2, 'cow', '소'),
       (2, 'elephant', '코끼리'),
       (2, 'bear', '곰'),
       (2, 'zebra', '얼룩말'),
       (2, 'giraffe', '기린'),
       (4, 'frisbee', '프리스비'),
       (4, 'skis', '스키'),
       (4, 'snowboard', '스노 보드'),
       (4, 'sports ball', '스포츠 공'),
       (4, 'kite', '연'),
       (4, 'baseball bat', '야구 방망이'),
       (4, 'baseball glove', '야구 장갑'),
       (4, 'skateboard', '스케이트 보드'),
       (4, 'surfboard', '서핑 보드'),
       (4, 'tennis racket', '테니스 라켓'),
       (3, 'banana', '바나나'),
       (3, 'apple', '사과'),
       (3, 'sandwich', '샌드위치'),
       (3, 'orange', '오렌지'),
       (3, 'broccoli', '브로콜리'),
       (3, 'carrot', '당근'),
       (3, 'hot dog', '핫도그'),
       (3, 'pizza', '피자'),
       (3, 'donut', '도넛'),
       (3, 'cake', '케이크'),
       (5, 'traffic light', '신호등'),
       (5, 'fire hydrant', '소화전'),
       (5, 'stop sign', '정지 신호'),
       (5, 'parking meter', '주차요금 정산기'),
       (5, 'bench', '의자'),
       (5, 'backpack', '배낭'),
       (5, 'umbrella', '우산'),
       (5, 'handbag', '손가방'),
       (5, 'tie', '넥타이'),
       (5, 'suitcase', '여행 가방'),
       (5, 'bottle', '병'),
       (5, 'wine glass', '와인 잔'),
       (5, 'cup', '컵'),
       (5, 'fork', '포크'),
       (5, 'knife', '칼'),
       (5, 'spoon', '숟가락'),
       (5, 'bowl', '그릇'),
       (5, 'chair', '의자'),
       (5, 'couch', '소파'),
       (5, 'potted plant', '화분'),
       (5, 'bed', '침대'),
       (5, 'dining table', '식탁'),
       (5, 'toilet', '화장실'),
       (5, 'tv', 'TV'),
       (5, 'laptop', '노트북'),
       (5, 'mouse', '마우스'),
       (5, 'remote', '리모컨'),
       (5, 'keyboard', '키보드'),
       (5, 'cell phone', '휴대 전화'),
       (5, 'microwave', '전자레인지'),
       (5, 'oven', '오븐'),
       (5, 'toaster', '토스터'),
       (5, 'sink', '싱크대'),
       (5, 'refrigerator', '냉장고'),
       (5, 'book', '도서'),
       (5, 'clock', '시계'),
       (5, 'vase', '물병'),
       (5, 'scissors', '가위'),
       (5, 'teddy bear', '곰 인형'),
       (5, 'hair drier', '헤어 드라이어'),
       (5, 'toothbrush', '칫솔'),
       (6, 'person', '사람');
