insert into sticker (file_path)
values ('jungle/001-toucan.png'),
       ('jungle/002-monkey.png'),
       ('jungle/003-waterfall.png'),
       ('jungle/004-palm tree.png'),
       ('jungle/005-castaway.png'),
       ('jungle/006-jungle.png'),
       ('jungle/007-hippopotamus.png'),
       ('jungle/008-plant.png'),
       ('jungle/009-chameleon.png'),
       ('jungle/010-backpack.png'),
       ('jungle/011-carnivorous plant.png'),
       ('jungle/012-frog.png'),
       ('jungle/013-sign.png'),
       ('jungle/014-gorilla.png'),
       ('jungle/015-jaguar.png'),
       ('jungle/016-snake.png'),
       ('jungle/017-explorer.png'),
       ('jungle/018-truck.png'),
       ('jungle/019-compass.png'),
       ('jungle/020-map.png'),
       ('jungle/021-explorer hat.png'),
       ('jungle/022-macaw.png'),
       ('jungle/023-elephant.png'),
       ('jungle/024-binoculars.png'),
       ('jungle/025-machete.png'),
       ('jungle/026-canteen.png'),
       ('jungle/027-explorer.png'),
       ('jungle/028-cave.png'),
       ('jungle/029-lion.png'),
       ('jungle/030-flamingo.png'),
       ('jungle/031-butterfly.png'),
       ('jungle/032-heliconia.png'),
       ('jungle/033-boots.png'),
       ('jungle/034-tiger.png'),
       ('jungle/035-piranha.png'),
       ('jungle/036-tarantula.png'),
       ('jungle/037-koala.png'),
       ('jungle/038-tree.png'),
       ('jungle/039-volcano.png'),
       ('jungle/040-lemur.png'),
       ('jungle/041-cabin.png'),
       ('jungle/042-flower.png'),
       ('jungle/043-vine.png'),
       ('jungle/044-lotus.png'),
       ('jungle/045-snail.png'),
       ('jungle/046-crocodile.png'),
       ('jungle/047-sloth.png'),
       ('jungle/048-platypus.png'),
       ('jungle/049-mushroom.png'),
       ('jungle/050-dragon fly.png');
