INSERT INTO `word` (`theme_id`, `word`)
VALUES (1, 'bicycle'),
       (1, 'car'),
       (1, 'motorcycle'),
       (1, 'airplane'),
       (1, 'bus'),
       (1, 'train'),
       (1, 'truck'),
       (1, 'boat'),
       (2, 'bird'),
       (2, 'cat'),
       (2, 'dog'),
       (2, 'horse'),
       (2, 'sheep'),
       (2, 'cow'),
       (2, 'elephant'),
       (2, 'bear'),
       (2, 'zebra'),
       (2, 'giraffe'),
       (4, 'frisbee'),
       (4, 'skis'),
       (4, 'snowboard'),
       (4, 'sports ball'),
       (4, 'kite'),
       (4, 'baseball bat'),
       (4, 'baseball glove'),
       (4, 'skateboard'),
       (4, 'surfboard'),
       (4, 'tennis racket'),
       (3, 'banana'),
       (3, 'apple'),
       (3, 'sandwich'),
       (3, 'orange'),
       (3, 'broccoli'),
       (3, 'carrot'),
       (3, 'hot dog'),
       (3, 'pizza'),
       (3, 'donut'),
       (3, 'cake'),
       (5, 'traffic light'),
       (5, 'fire hydrant'),
       (5, 'stop sign'),
       (5, 'parking meter'),
       (5, 'bench'),
       (5, 'backpack'),
       (5, 'umbrella'),
       (5, 'handbag'),
       (5, 'tie'),
       (5, 'suitcase'),
       (5, 'bottle'),
       (5, 'wine glass'),
       (5, 'cup'),
       (5, 'fork'),
       (5, 'knife'),
       (5, 'spoon'),
       (5, 'bowl'),
       (5, 'chair'),
       (5, 'couch'),
       (5, 'potted plant'),
       (5, 'bed'),
       (5, 'dining table'),
       (5, 'toilet'),
       (5, 'tv'),
       (5, 'laptop'),
       (5, 'mouse'),
       (5, 'remote'),
       (5, 'keyboard'),
       (5, 'cell phone'),
       (5, 'microwave'),
       (5, 'oven'),
       (5, 'toaster'),
       (5, 'sink'),
       (5, 'refrigerator'),
       (5, 'book'),
       (5, 'clock'),
       (5, 'vase'),
       (5, 'scissors'),
       (5, 'teddy bear'),
       (5, 'hair drier'),
       (5, 'toothbrush'),
       (6, 'person');
